### ISSUE TITLE
[Suggestion] Psuedo new-tab minimal experience with a random shot.

### ISSUE THREAD

**Issue by mroosa** [Fraulk/second-look#1]
I remember talking to someone a while back about the plausibility of a new-tab extension that pulled in Framed HOF images, but thought it would be a great idea for second look too. Personally, I use _Tabliss_ to achieve this, which pulls images from unsplash.com.

The way I can see it working without making a full blown extension, is to make a specific URL, like /new-tab, that incorporates a minimal new tab experience, showing the date/time, user and picture information, possibly with some settings to allow customization.

Tabliss inspired example uploaded.

![Screenshot 2024-09-02 at 10 43 56 PM](https://github.com/user-attachments/assets/4223b60d-0202-4c29-96a3-b73c7a886e1a)

**Comment by mroosa** [comment]
I was using Tabliss as a reference for layout/content. I know there are a bunch of minimal new tab experiences out there, but the main thing most have is a date/time. I figured something similar could work for showing off second look/hof stuff.

**Comment by Fraulk** [comment]
By the way, shots are saved as JPEG at 50% quality, so you might see some banding like this one
![sammirllm-1725463109 018](https://github.com/user-attachments/assets/00c48505-fc39-467c-8c45-a3740455316d)

**Comment by Fraulk** [comment]
Ok it's done, you can access it here [https://second-look.netlify.app/new-tab](https://second-look.netlify.app/new-tab)
